spring:
  application.name: @name@

  datasource:
    username: flow-creator
    password: flow-creator
    hikari.pool-name: ${spring.application.name}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/flow-creator

  #JPA
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: com.emanuelvictor.api.functional.flowcreator.infrastructure.jpa.fk.CustomNamingStrategy
    show-sql: true
    open-in-view: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.default_schema: public
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
        metadata_builder_contributor: com.emanuelvictor.api.functional.flowcreator.infrastructure.jpa.function.SqlFunctionsMetadataBuilderContributor
      jakarta:
        persistence:
          sharedCache:
            mode: ALL

  flyway:
    enabled: true
    locations: classpath:db/migrations
    sql-migration-prefix:
    baseline-on-migrate: true
    baseline-version: 0
    fail-on-missing-locations: true

  health:
    ldap:
      enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: [ 'health', 'info', 'flyway' , 'logfile' ]
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    flyway:
      enabled: true
    logfile:
      enabled: true
      external-file: /var/log/${spring.application.name}/${spring.application.name}.log

logging:
  file:
    name: /var/log/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO
    org.hibernate: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.context.support: INFO

info:
  name: flow-creator
  description: 'Flow Creator'
  version: @project.version@-@project.build-number@
  environment: alpha
