spring:

  #STATIC RESOURCES
  resources.static-locations: classpath:/META-INF/resources/
  resources.chain:
    cache: false
    strategy.content.enabled: true
    strategy.content.paths: /**

  #THYMELEAF
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/META-INF/resources/
    suffix: .html

  flyway:
    enabled: true
    check-location: true
    locations: classpath:db/migrations
    sql-migration-prefix:
    baseline-on-migrate: true
    baseline-version: 0
#
#  thymeleaf:
#    enabled: true
#    cache: false
#    check-template: true
#    check-template-location: true

#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

#server:
#  servlet:
#    session:
#      persistent: false

management:
  health:
    ldap:
      enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: ['health', 'info', 'flyway' , 'logfile']
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    flyway:
      enabled: true
    logfile:
      enabled: true
      external-file: /var/log/${spring.application.name}/${spring.application.name}.log

logging:
  file:
    name: /var/log/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO
    org.hibernate: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.context.support: INFO

info:
  name: flow-creator
  description: 'Flow Creator'
  version: @project.version@-@project.build-number@
  environment: @active.profile@
